[package]
name = "bevy_game_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"
rayon = "1.7.0"

[profile.dev.package."*"]
opt-level = 3
